@BaseUrl = http://localhost:8080

###
GET {{BaseUrl}}

###
POST {{BaseUrl}}/createUser
Content-Type: application/json

{
    "email": "cassiano@test.com",
    "password": "test!dd",
    "name": "Cassiano",
    "age": 28
}

###
GET {{BaseUrl}}/getUserById/6a37597259e4c612f63f7d05
Accept: application/json
Authorization: 

###
GET {{BaseUrl}}/getUserByEmail/email
Accept: application/json
Authorization: 

###
PUT  {{BaseUrl}}/updateUser/PUT_USER_ID_HERE
Content-Type: application/json

{
    "name": "Cassiano",
    "age": 28
}

###
DELETE  {{BaseUrl}}/deleteUser/6a3628ff71ad6f0c37631596

###
POST {{BaseUrl}}/login
Content-Type: application/json

{
    "email": "cassiano@test.com",
    "password": "test!dd"
}