@BaseUrl = http://localhost:8080

###

GET {{BaseUrl}}

###

POST {{BaseUrl}}/createUser
Content-Type: application/json

{
    "email": "cassiano@test.com",
    "password": "test!dd",
    "name": "Cassiano",
    "age": 28
}

###

PUT  {{BaseUrl}}/updateUser/:id
Content-Type: application/json

{
    "name": "Cassiano",
    "age": 28
}